### ISSUE TITLE
First unreleased version in changelog doesn't get replaced

### ISSUE THREAD

**Issue by cdupuis** [atomist/sdm-pack-changelog#1]
The changelog goal fails convert the following changelog into one with a proper released version. This is because of the link using `tree` instead of compare urls. This `tree` url format is only for the first version.

```
# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](http://keepachangelog.com/)
and this project adheres to [Semantic Versioning](http://semver.org/).

## [Unreleased](https://github.com/atomist/sentry-automation/tree/HEAD)

### Added

-   This is my first test issue. [#1](https://github.com/atomist/sentry-automation/issues/1)
-   Some manual issue was added.

### Fixed

-   adada. [#2](https://github.com/atomist/sentry-automation/issues/2
```

**Comment by ddgenome** [comment]
Typically I never have the unreleased link use the tree form. Is that what our template for the initial change log does?

**Comment by cdupuis** [comment]
Yeah, because you can't use a compare url as there is nothing to compare against, or is there?

**Comment by cdupuis** [comment]
I'm happy to change the template with a different url for the first version.
